Repository kj415j45/kjBot, pull requests merged in 2018-07, with the labels that each got.

#69 Update to 2.5
  Open Source Licenses/kilingzhang/coolq-php-sdk/LICENSE
  README.md
  SDK/API.php
  SDK/CoolQ.php
  config.ini.example
  module/recordStat/global.php
  module/recordStat/me.php
  module/unsleep/main.php
  public/tools/Autoload.php
  public/tools/frame.php
  public/tools/statDB.php
Labels: SDK, feature, framework

#76 Patch 2.5
  module/help/main.php
  module/help/pixiv/IID.php
  module/pixiv/IID.php
  module/pixiv/search.php
  module/pixiv/tools.php
  module/voice/main.php
Labels: feature

#81 添加在windows平台build的功能
  build.cmd
  build.php
  build.sh
  run.cmd
Labels: Windows
